"""create_runs

Revision ID: f94c142bef11
Revises: 7a0cb6ee1f48
Create Date: 2026-09-02 15:53:18.741765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f94c142bef11'
down_revision: Union[str, Sequence[str], None] = '7a0cb6ee1f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('avg_pace_sec', sa.Integer(), sa.Computed('(duration_sec / NULLIF(distance_km, 0))::integer', persisted=True), nullable=True),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weather_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_type IN ('easy','tempo','interval','long_run','race','recovery')", name='ck_runs_run_type'),
    sa.CheckConstraint('distance_km > 0', name='ck_runs_distance_positive'),
    sa.CheckConstraint('duration_sec > 0', name='ck_runs_duration_positive'),
    sa.CheckConstraint('rpe BETWEEN 1 AND 10', name='ck_runs_rpe'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_user_date', 'runs', ['user_id', 'run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_runs_user_date', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
