"""create_goals_and_weekly_plans

Revision ID: f98c4ca51889
Revises: f94c142bef11
Create Date: 2026-09-03 00:08:46.888837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f98c4ca51889'
down_revision: Union[str, Sequence[str], None] = 'f94c142bef11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('weekly_km_target', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('race_name', sa.String(length=200), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('race_target_time', sa.Integer(), nullable=True),
    sa.Column('race_distance_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("goal_type IN ('weekly_volume','race')", name='ck_goals_goal_type'),
    sa.CheckConstraint("status IN ('active','completed','abandoned')", name='ck_goals_status'),
    sa.CheckConstraint('weekly_km_target IS NULL OR weekly_km_target > 0', name='ck_goals_weekly_km_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goals_user_active', 'goals', ['user_id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('weekly_plans',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('planned_sessions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('total_planned_km', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('adjustments_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='unique_user_week')
    )
    op.create_unique_constraint('unique_user_run_date', 'runs', ['user_id', 'run_date', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_run_date', 'runs', type_='unique')
    op.drop_table('weekly_plans')
    op.drop_index('idx_goals_user_active', table_name='goals', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('goals')
    # ### end Alembic commands ###
